name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        working-directory: coredns
        run: go test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-target: ["windows", "darwin", "linux-amd64", "linux-arm64"]
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        working-directory: coredns
        run: make clean build-${{ matrix.build-target }}

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          path: coredns/build/*
